red me

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -4,6 +4,12 @@
 # Find the PID of the Gunicorn master process
 pid=$(pgrep gunicorn)
 
-# Send the USR2 signal to the master process to gracefully reload configurations
-kill -s USR2 $pid
+if [[ -n $pid ]]; then
+    # Send the USR2 signal to the master process to gracefully reload configurations
+    kill -s USR2 "$pid"
+    echo "Gunicorn configurations reloaded and workers restarted gracefully."
+else
+    echo "Gunicorn master process not found. Check if Gunicorn is running."
+    exit 1
+fi
 
